#!/usr/bin/perl -w

use strict;
use Data::Dumper;

sub clean_dir {
  my $dirname = shift;
  my $entries;
  if (open (ENTRIES, "<", "$dirname/CVS/Entries")) {
    while (<ENTRIES>) {
      if (m(^/([^/]+)/)) {
        $entries->{$1} = 'file';
      } elsif (m(^D/([^/]+)////$)) {
        $entries->{$1} = 'directory';
      } else {
        warn "Can't parse $_";
      }
    }
    close (ENTRIES)
      or warn "Can't close filehandle from $dirname/CVS/Entries: $!";
    #warn Data::Dumper->Dump ([$entries], [qw(entries)]);
    opendir (VICTIM, $dirname) or die "Can't opendir $dirname: $!";
    while (my $v = readdir (VICTIM)) {
      next if ($v =~ m(^\.{1,2}$));
      next if (exists $entries->{$v});
      next unless (-f "$dirname/$v");

      warn "Pretend I'm deleting file $dirname/$v" ;
  }
    closedir (VICTIM);
  } else {
    warn "Can't open $dirname/CVS/Entries for reading: $!";
  }
}

clean_dir ($_) foreach (@ARGV);
