(require 'random)
(define insult

  (let ((insults 0))
    ;;To construct a Shakespearean insult, combine one word from each of the
    ;;three columns below, and preface it with "Thou":

    (define data
      (list
       ;;    Column 1          Column 2              Column 3
       (list "artless"         "base-court"          "apple-john")
       (list "bawdy"           "bat-fowling"         "baggage")
       (list "beslubbering"    "beef-witted"         "barnacle")
       (list "bootless"        "beetle-headed"       "bladder")
       (list "churlish"        "boil-brained"        "boar-pig")
       (list "cockered"        "clapper-clawed"      "bugbear")
       (list "clouted"         "clay-brained"        "bum-bailey")
       (list "craven"          "common-kissing"      "canker-blossom")
       (list "currish"         "crook-pated"         "clack-dish")
       (list "dankish"         "dismal-dreaming"     "clotpole")
       (list "dissembling"     "dizzy-eyed"          "coxcomb")
       (list "droning"         "doghearted"          "codpiece")
       (list "errant"          "dread-bolted"        "death-token")
       (list "fawning"         "earth-vexing"        "dewberry")
       (list "fobbing"         "elf-skinned"         "flap-dragon")
       (list "froward"         "fat-kidneyed"        "flax-wench")
       (list "frothy"          "fen-sucked"          "flirt-gill")
       (list "gleeking"        "flap-mouthed"        "foot-licker")
       (list "goatish"         "fly-bitten"          "fustilarian")
       (list "gorbellied"      "folly-fallen"        "giglet")
       (list "impertinent"     "fool-born"           "gudgeon")
       (list "infectious"      "full-gorged"         "haggard")
       (list "jarring"         "guts-griping"        "harpy")
       (list "loggerheaded"    "half-faced"          "hedge-pig")
       (list "lumpish"         "hasty-witted"        "horn-beast")
       (list "mammering"       "hedge-born"          "hugger-mugger")
       (list "mangled"         "hell-hated"          "joithead")
       (list "mewling"         "idle-headed"         "lewdster")
       (list "paunchy"         "ill-breeding"        "lout")
       (list "pribbling"       "ill-nurtured"        "maggot-pie")
       (list "puking"          "knotty-pated"        "malt-worm")
       (list "puny"            "milk-livered"        "mammet")
       (list "qualling"        "motley-minded"       "measle")
       (list "rank"            "onion-eyed"          "minnow")
       (list "reeky"           "plume-plucked"       "miscreant")
       (list "roguish"         "pottle-deep"         "moldwarp")
       (list "ruttish"         "pox-marked"          "mumble-news")
       (list "saucy"           "reeling-ripe"        "nut-hook")
       (list "spleeny"         "rough-hewn"          "pigeon-egg")
       (list "spongy"          "rude-growing"        "pignut")
       (list "surly"           "rump-fed"            "puttock")
       (list "tottering"       "shard-borne"         "pumpion")
       (list "unmuzzled"       "sheep-biting"        "ratsbane")
       (list "vain"            "spur-galled"         "scut")
       (list "venomed"         "swag-bellied"        "skainsmate")
       (list "villainous"      "tardy-gaited"        "strumpet")
       (list "warped"          "tickle-brained"      "varlet")
       (list "wayward"         "toad-spotted"        "vassal")
       (list "weedy"           "unchin-snouted"      "whey-face")
       (list "yeasty"          "weather-bitten"      "wagtail")))

    (define subjects (list "Thou" "Thouest's wyffe is a" "Thouest's mother is a"))
    (lambda ()
      (set! insults (+ 1 insults))
      (let ((1st-adjective (car   (list-ref data (random (length data)))))
	    (2nd-adjective (cadr  (list-ref data (random (length data)))))
	    (noun          (caddr (list-ref data (random (length data))))))
	(string-append
	 (list-ref subjects (remainder insults (length subjects)))
	 " "
	 1st-adjective " " 2nd-adjective " " noun)))))
