# -*-python-*-

Program ('anagrams',
         ['anagrams.d',
          'bag.d',
          'dictionary.d',
          'mpz.d',
          'gmppool.d'],
         DFLAGS = ['-unittest', '-g', '-pg'],
         LIBS = ['gmp'],
         LINKFLAGS = ['-pg'])
