# -*-python-*-
env = Environment(DFLAGS = ['-unittest', '-g'])
env.Program ('anagrams',
             ['anagrams.d',
              'bag.d',
              'dictionary.d',
              'mpz.d',
              'gmppool.d'],
             LIBS = ['gmp'])
