#!/bin/sh

./run-bot.ss                                    \
--delicious frumble4                            \
--host irc.freenode.org                         \
--nick rudybot                                  \
--nickserv fartulosity                          \
--planet                                        \
--verbose                                       \
-c '#emacs'                                     \
-c '#scheme'                                    \
-c '#bots'                                      \
-c '#scheme-bots'                               \
-c '##cinema'
