#!/usr/bin/env python

# Read some dependency information generated by my hacked-up version
# GNU make, and write a .dot file suitable for processing by `dot'.

# The dependency information is zero or more lines that look like this:

#   target : prerequisite
 
# both TARGET and PREREQUISITE are strings that contain neither
# whitespace nor colons.

# This is the sort of thing that a Perl whiz could probably do in one
# line, but I ain't no Perl whiz, and besides, this is easier to read.

import re, string

def print_spiffed_up_line (line):
    target, prerequisite = re.split (' : ', string.rstrip (line))
    result = '"' + target + '"' + ' -> ' + '"' + prerequisite + '"'
    print result
    return result

file = open (".GNUmake-dependencies")
lines = file.readlines ()
print "digraph bob {"
print "rankdir=LR;\ncenter=true;\nratio=auto;\npage=\"8.5,11\""
map (print_spiffed_up_line, lines)
print "}"
file.close ()
