(require 'random)
(require 'pretty-print)

;; After one of Doug Hofstadter's "Metamagical Themas" columns in
;; Scientific American.

(define (expand thing)
  (define maybe-expand
    (let ((smaller (lambda (number) (* number 0.5)))
	  (expansions '((a . (A l p h a))
			(b . (B r a v o))
			(c . (C h a r l i e))
			(d . (D e l t a))
			(e . (E c h o))
			(f . (F o x t r o t))
			(g . (G o l f))
			(h . (H o t e l))
			(i . (I n d i a))
			(j . (J u l i e t))
			(k . (K i l o))
			(l . (L i m a))
			(m . (M i k e))
			(n . (N o v e m b e r))
			(o . (O s c a r))
			(p . (P a p a))
			(q . (Q u e b e c))
			(r . (R o m e o))
			(s . (S i e r r a))
			(t . (T a n g o))
			(u . (U n i f o r m))
			(v . (V i c t o r))
			(w . (W h i s k e y))
			(x . (X r a y))
			(y . (Y a n k e e))
			(z . (Z u l u)))))
      (lambda (thing probability)
	(cond ((null? thing)
	       '())
	      ((list? thing)
	       (cons (maybe-expand (car thing)
				   probability)
		     (maybe-expand (cdr thing)
				   probability)))
	      ((symbol? thing)
	       (if (> probability (random 1.0))
		   (maybe-expand  (cdr (assq thing expansions))
				  (smaller probability))
		 thing))))))
  (maybe-expand thing 1))

(pretty-print (expand '(f r i e d e g g s)))
